pr:
- master

variables:
  snyk_token: $(Snyk-Token)
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/terraform/azure'

pool:
  vmImage: 'ubuntu-latest'
  
stages:

  - stage: Scanning
    jobs:
    # - job: Checkov
    #   steps:
    #   - template: templates/checkov.yml
    # - job: TFSec
    #   steps:
    #   - template: templates/tfsec.yml
    - job: Terrascan
      steps:
      - template: templates/terrascan.yml
      
    
