# azure-pipelines.yml

trigger: 
- master

variables:
  SNYK_TOKEN: $(Snyk-Token)

pool:
  vmImage: 'ubuntu-latest'
  
stages:

  - stage: Scan
    jobs:
    # - job: Checkov
    #   steps:
    #   - template: templates/checkov.yml
    # - job: TFSec
    #   steps:
    #   - template: templates/tfsec.yml
    - job: Snyk_IaC
      steps:
      - template: templates/snyk_iac.yml
      
    
