# azure-pipelines.yml

trigger: 
- master

# pr:
# - checkov

pool:
  vmImage: 'ubuntu-latest'
  
stages:

  - stage: Scan
    jobs:
    - job: Checkov_Docker 
      steps:
      - template: templates/checkov.yml

  - stage: Scan
    jobs:
    - job: TFSec_Docker 
      steps:
      - template: templates/tfsec.yml
      
    
